-- Define our package loader.
require "_UnmanagedExt/ModuleLoader"

-- Check to see if Ext is already defined
if (type(Engine) ~= nil) then
	Engine = {}
end

-- Check to see if Resources is already defined
if (type(Resources) ~= nil) then
	Resources = {}
end

-- Define our IDE extensions table
require "Engine.Model"
require "Engine.Image"
require "Engine.Audio"
require "Engine.Template"
require "Engine.Area"
require "Engine.World"

require "Resources"		-- This file is auto-generated by the IDE to make static links to the game's resources.