-- Define our package loader.
require "_UnmanagedExt/ModuleLoader"

-- Check to see if Ext is already defined
if (type(Ext) ~= nil) then
	Ext = {}
end

-- Check to see if Resources is already defined
if (type(Resources) ~= nil) then
	Resources = {}
end

-- Define our IDE extensions table
Ext.IDE = {}

require "Ext.IDE.Model"
require "Ext.IDE.Image"
require "Ext.IDE.Audio"
require "Ext.IDE.Template"
require "Ext.IDE.Area"
require "Ext.IDE.World"

require "Resources"		-- This file is auto-generated by the IDE to make static links to the game's resources.