#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Jan 29 17:55:52 2009

import wx
import os

class InstallExtensionsDialog(wx.Dialog):
    def __init__(self, installhandle, cancelhandle, ide):
        # begin wxGlade: dlgExtensions.__init__
        wx.Dialog.__init__(self, ide, style=wx.DEFAULT_DIALOG_STYLE)
        self.bitmap_button_1 = wx.BitmapButton(self, -1, wx.Bitmap(ide.appdir+"/Data/images/dlg_extensions.png", wx.BITMAP_TYPE_ANY), style=wx.NO_BORDER)
        self.list_box_1 = InstallExtensionsList(self, -1)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.btnClose = wx.Button(self, -1, "Close")
        self.btnInstall = wx.Button(self, -1, "Install Extension")

        self.__set_properties()
        self.__do_layout()

        self.okayButtonCaller = installhandle
        self.cancelButtonCaller = cancelhandle

        wx.EVT_BUTTON(self, self.btnClose.GetId(), self.cancelCalled)
        wx.EVT_BUTTON(self, self.btnInstall.GetId(), self.okayCalled)

        self.CentreOnScreen()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: dlgExtensions.__set_properties
        self.SetTitle("Install Extensions")
        self.SetSize((511, 514))
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        self.btnInstall.SetMinSize((150, 23))
        self.btnInstall.SetToolTipString("Install the currently selected extension into the project.")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: dlgExtensions.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.bitmap_button_1, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 3)
        sizer_2.Add(self.list_box_1, 2, wx.EXPAND, 0)
        sizer_2.Add(self.text_ctrl_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 2, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_3.Add(self.btnClose, 0, wx.LEFT|wx.RIGHT|wx.TOP, 3)
        sizer_3.Add(self.btnInstall, 0, wx.RIGHT|wx.TOP|wx.EXPAND, 3)
        sizer_1.Add(sizer_3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade
    
    def cancelCalled(self, event):
        self.cancelButtonCaller()
        self.EndModal(0)

    def okayCalled(self, event):
        self.okayButtonCaller()
        self.EndModal(0)

class InstallExtensionsList(wx.HtmlListBox):
    def __init__(self, container, idd):
        wx.HtmlListBox.__init__(self, container, idd)

        self.extensions = list()
        self.extensions.append({ 'name': "Highscore List",
                               'namespace': "Highscore",
                               'description': "Provides a system where you can automatically submit and retrieve highscores from RoketGames.",
                               'author': "Roket Productions",
                               'version': "0.1",
                               'cost': "Free"
                             })
        self.extensions.append({ 'name': "3rd Person camera",
                               'namespace': "LazyCamera",
                               'description': "Provides a 3rd person camera for watching scene nodes.",
                               'author': "Roket Productions",
                               'version': "0.1",
                               'cost': "Free"
                             })
        self.SetItemCount(2)

    def OnGetItem(self, num):
##        text = "<div style='padding:3px;'>"
##        text += "<div style='float:right;'>Ext."+self.extensions[num]["namespace"]+"</div>"
##        text += "<div style='font-weight:bold;'>"+self.extensions[num]["name"]+"</div>"
##        text += "<div style='padding:5px; padding-top:10px; padding-bottom:10px; font-size:12px;'>"+self.extensions[num]["description"]+"</div>"
##        text += "<div style='float:right;'>"+self.extensions[num]["cost"]+"</div><div style='font-style:italic;'>"+self.extensions[num]["author"]+", V"+self.extensions[num]["version"]+"</div>"
##        text += "</div>"
        text = '<table width="100%" border="0" cellspacing="0" cellpadding="5">'
        text += '        <tr>'
        text += '                <td><b>'+self.extensions[num]["name"]+'</b></td>'
        text += '                <td align="right">Ext.'+self.extensions[num]["namespace"]+'</td>'
        text += '        </tr>'
        text += '        <tr>'
        text += '                <td colspan="2"><font size="-1">'+self.extensions[num]["description"]+'</font></td>'
        text += '        </tr>'
        text += '        <tr>'
        text += '                <td>'
        if (num == 1):
            text += '<font face="Verdana" color="#006633" size="-2"><b>INSTALLED</b></font>'
        text += '</td>'
        text += '                <td align="right"><i>'+self.extensions[num]["author"]+', V'+self.extensions[num]["version"]+'</i></td>'
        text += '        </tr>'
        text += '</table>'
        return text

# end of class dlgExtensions
