/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#ifndef CLASS_Engine_Collections_RColor
#define CLASS_Engine_Collections_RColor

/* Imports */

/* Using declarations */

namespace Engine { namespace Collections
{
    /* Begin class declaration */
    class RColor : public RObject
    {
        /* Variable declarations */

        /* Method and constructor declarations */

        /* Automatic property getter-setter declarations */
    };
} 
} 

#endif
