/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "E.Collections/RColor.h"

namespace Engine { namespace Collections
{
    /* Variable definitions */

    /* Method and constructor definitions */
    /* Automatic property getter-setter definitions */
} 
} 

