-- Define our package loader.
require "_Unmanaged/ModuleLoader"

-- Define our IDE extensions table
require "Engine.Area"
require "Engine.Audio"
require "Engine.Events"
require "Engine.Image"
require "Engine.Model"
require "Engine.Template"
require "Engine.World"

--require "Resources"		-- This file is auto-generated by the IDE to make static links to the game's resources.



